FROM oven/bun:latest

WORKDIR /app

# Copy root package.json
COPY package.json ./
COPY apps/frontend/package.json ./apps/frontend/

# Install dependencies
RUN bun install

# Copy source code
COPY apps/frontend ./apps/frontend

EXPOSE 5173

WORKDIR /app/apps/frontend
CMD ["bun", "run", "dev"]
